### ISSUE TITLE
Error: spawn git ENOENT

### ISSUE THREAD

**Issue by benjamin21st** [iambibhas/vscode-git-easy#4]
Hi, 

I'm using VS Code 1.8.1 on Windows 7. 

When I try to do any giteasy commands, it throws error: 
```
Error: spawn git ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```
Any idea what might have caused this? 
Thank you!

**Comment by benjamin21st** [comment]
Upon an inspection of the output, it seems that it is not recognizing my git repository. My workspace root contains the .git folder, and I have a bunch of git submodules in one of the child folders of root. I hope these information helps.
